//This file will hold our function declarations for redux.
//It is reccommend to use a file like this because JS will throw more useful errors this way.
const constants = {

    UPDATE_USER_LOGGEDIN: "UPDATE_USER_LOGGEDIN",
    UPDATE_MODAL_OPEN: "UPDATE_MODAL_OPEN",
    UPDATE_MODAL_COMPONENT: "UPDATE_MODAL_COMPONENT",
    UPDATE_SNACKBAR_OPEN: "UPDATE_SNACKBAR_OPEN",
    UPDATE_SNACKBAR_CONTENT: "UPDATE_SNACKBAR_CONTENT",
    UPDATE_CURRENT_USER_ID: 'UPDATE_CURRENT_USER_ID',
    UPDATE_CURRENT_USER_PERMISSIONS: 'UPDATE_CURRENT_USER_PERMISSIONS',

    UPDATE_CURRENT_USER_EVENT_RESERVATIONS: 'UPDATE_CURRENT_USER_EVENT_RESERVATIONS',
    ADD_CURRENT_USER_EVENT_RESERVATION: 'ADD_CURRENT_USER_EVENT_RESERVATION',
    UPDATE_CURRENT_USER_EVENT_RESERVATION: 'UPDATE_CURRENT_USER_EVENT_RESERVATION',
    DELETE_CURRENT_USER_EVENT_RESERVATION: 'DELETE_CURRENT_USER_EVENT_RESERVATION',

    UPDATE_PROFILE_ID: 'UPDATE_PROFILE_ID',
    UPDATE_PROFILE_DATA: 'UPDATE_PROFILE_DATA',
    UPDATE_PROFILE_DATA_ROLE: 'UPDATE_PROFILE_DATA_ROLE',
    UPDATE_PROFILE_DATA_LOADED: 'UPDATE_PROFILE_DATA_LOADED',
    UPDATE_CURRENT_ROLE_ID: "UPDATE_CURRENT_ROLE_ID",
    UPDATE_CURRENT_DELETE_ID: 'UPDATE_DELETE_ID',
    UPDATE_CURRENT_EVENT: 'UPDATE_CURRENT_EVENT',

    UPDATE_ALL_USERS: 'UPDATE_ALL_USERS',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

    UPDATE_ALL_EVENTS: 'UPDATE_ALL_EVENTS',
    ADD_EVENT: 'ADD_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',

    CLEAR_USER_INFO: 'CLEAR_USER_INFO',

    UPDATE_ACTIVE_MODULE: 'UPDATE_ACTIVE_MODULE',

    UPDATE_ACTIVE_MENU: 'UPDATE_ACTIVE_MENU',

    UPDATE_ACTIVE_VIEW: 'UPDATE_ACTIVE_VIEW',
}

export default constants
