//This file will hold our function declarations for redux.
//It is reccommend to use a file like this because JS will throw more useful errors this way.
const constants = {

    UPDATE_USER_LOGGEDIN: "UPDATE_USER_LOGGEDIN",
    UPDATE_MODAL_OPEN: "UPDATE_MODAL_OPEN",
    UPDATE_MODAL_COMPONENT: "UPDATE_MODAL_COMPONENT",
    UPDATE_CURRENT_USER_ID: 'UPDATE_CURRENT_USER_ID',
    UPDATE_CURRENT_USER_PERMISSIONS: 'UPDATE_CURRENT_USER_PERMISSIONS',
    UPDATE_PROFILE_ID: 'UPDATE_PROFILE_ID',
    UPDATE_PROFILE_DATA: 'UPDATE_PROFILE_DATA',
    UPDATE_PROFILE_DATA_ROLE: 'UPDATE_PROFILE_DATA_ROLE',
    UPDATE_PROFILE_DATA_LOADED: 'UPDATE_PROFILE_DATA_LOADED',
    UPDATE_CURRENT_ROLE_ID: "UPDATE_CURRENT_ROLE_ID",
    UPDATE_CURRENT_DELETE_ID: 'UPDATE_DELETE_ID',

    UPDATE_ALL_USERS: 'UPDATE_ALL_USERS',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

    CLEAR_USER_INFO: 'CLEAR_USER_INFO',

    UPDATE_ACTIVE_MODULE: 'UPDATE_ACTIVE_MODULE',

    UPDATE_ACTIVE_MENU: 'UPDATE_ACTIVE_MENU',

    UPDATE_ACTIVE_VIEW: 'UPDATE_ACTIVE_VIEW',
}

export default constants
